flowchart LR
    classDef awsNode fill:#232F3E,stroke:#F90,stroke-width:2px,color:#FFF,font-size:14px;
    classDef userNode fill:#FF9900,stroke:#333,stroke-width:2px,color:#000,font-size:14px;

    A[Template YAML/JSON]:::userNode --> B[CloudFormation Stack (Create/Update)]:::awsNode

    B --> C[EC2 Instance (com EBS)]:::awsNode
    B --> D[S3 Bucket (com Políticas)]:::awsNode
    B --> E[IAM Role (para Lambda/EC2)]:::awsNode
    B --> F[Security Group (Firewall Rules)]:::awsNode

    F --> C
    F --> D
