flowchart LR
    classDef awsNode fill:#232F3E,stroke:#F90,stroke-width:2px,color:#FFF;
    classDef userNode fill:#FF9900,stroke:#333,stroke-width:2px,color:#000;

    A["Template YAML/JSON"]
    B["CloudFormation Stack (Create/Update)"]
    C["EC2 Instance (com EBS)"]
    D["S3 Bucket (com Politicas)"]
    E["IAM Role (para Lambda/EC2)"]
    F["Security Group (Firewall Rules)"]

    A:::userNode --> B:::awsNode
    B --> C:::awsNode
    B --> D:::awsNode
    B --> E:::awsNode
    B --> F:::awsNode
    F --> C
    F --> D
